name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Update repos
        run: sudo apt-get update
      - name: Upgrade system
        run: sudo apt-get upgrade -y
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Check the format
        run: cargo fmt --all -- --check
      - name: Check for any lints
        run: cargo clippy --all-targets --all-features -- -D clippy::pedantic
      - name: Check if it builds
        run: cargo check --all
      - name: Run the tests
        run: cargo test
