name: Main

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            components: rustfmt
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            components: clippy
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets -- -D clippy::pedantic

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
      - uses: actions/checkout@v3
      - run: cargo check --all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: cargo test
